# Basic appveyor configuration : CodeCakeBuilder does the job.
version: build{build}
branches:
  only:
  - master
  - develop
environment:
  MYGET_API_KEY:
    secure: UJHposYXJGXI9QzRjbxUN/qEBxMDfOVqKa1cB6JEqrXnSnRHB1Wu4EFEO9AGb8y/
init:
- git config --global core.autocrlf true
install:
  - ps: CodeCakeBuilder\Bootstrap.ps1
build_script:
- CodeCakeBuilder\bin\Release\CodeCakeBuilder.exe -nointeraction
test: off
